#!/usr/bin/env python

import sys, argparse, time, traceback, time
from dccexonsbc.utils import hardware_setup_function_from
from dccexonsbc.station import Station

def parse_accessory_id(s):
    if "," in s:
        return tuple([int(p) for p in s.split(",")])
    else:
        return int(s)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("module")
    parser.add_argument("accessory_id", type=parse_accessory_id,
                        help="An accessory id may be either a single integer "
                        "or a pair of integers as in “a,b”, the former "
                        "referring to a “linear” accessory id, the latter "
                        "to a pair as in address, subaddress.")

    args = parser.parse_args()

    hardware_setup = hardware_setup_function_from(args.module)
    
    if hardware_setup is None:
        raise ImportError("No hardware_setup() in " + args.module)

    station = Station()

    try:
        hardware_setup(station)

        agent = station.accessories.get(args.accessory_id, None)
        if agent is None:
            raise ImportError("No accessory %s (%s) defined in %s." % (
                repr(args.accessory_id), str(type(args.accessory_id)),
                args.module))

        accessory = agent.hardware

        while station.running:
            for state in accessory.states:
                print(state)
                accessory.set(state)
                time.sleep(1)
    finally:
        station.abort()

main()

