#!/usr/bin/env python

import sys, argparse, time, traceback, time
from dccexonsbc.utils import HardwareSetupArgumentParser
from dccexonsbc.station import Station

def main():
    parser = HardwareSetupArgumentParser()
    parser.add_argument("turnout_id", type=int)

    args = parser.parse_args()

    station = Station()

    try:
        parser.call_hardware_setup_for(station)

        turnout_agent = station.turnouts.get(args.turnout_id, None)
        if turnout_agent is None:
            raise ImportError("No turnout %i defined in %s." % (
                args.turnout_id, args.module))

        turnout = turnout_agent.hardware

        while station.running:
            for state in turnout.states:
                print(state)
                turnout.set(state)
                time.sleep(1)
    finally:
        station.abort()

main()

