#!/usr/bin/env python

import sys, argparse, time, traceback
from dccexonsbc.utils import hardware_setup_function_from
from dccexonsbc.station import Station

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("module")
    parser.add_argument("turnout_id", type=int)

    args = parser.parse_args()

    hardware_setup = hardware_setup_function_from(args.module)
    
    if hardware_setup is None:
        raise ImportError("No hardware_setup() in " + args.module)

    station = Station()

    try:
        hardware_setup(station)

        turnout_agent = station.turnouts.get(args.turnout_id, None)
        if turnout_agent is None:
            raise ImportError("No turnout %i defined in %s." % (
                args.turnout_id, args.module))

        turnout = turnout_agent
        while True:
            for state in turnout.states:
                print(state)
                turnout.set(state)
                time.sleep(1)
    finally:
        station.abort()

    
    
main()    

